export { defineComponent, createComponent } from './defineComponent'
export { SetupFunction, SetupContext } from './componentOptions'
export { ComponentInstance, ComponentRenderProxy } from './componentProxy'
export { Data } from './common'
export { PropType, PropOptions } from './componentProps'
